
#GAMMA = 0.99
#LAMBDA = 0.95
#EPSILON = 0.1
#LEARNING_RATE = 2.5e-4
#NUM_WORKERS = 1
#T = 128
#EPOCHS = 3
#BATCH_SIZE = 32 * NUM_WORKERS
#RENDER = True
#C1 = 1
#C2 = 0.00
#ENV_MAKER = gym.make
#ENV_ID = "CartPole-v0"
#STATE_TYPE = "OTHER"
#INPUT_SHAPE = [4, 2]
#ACTIONS = [0, 1]
#NUM_STEPS = 4e5
#LR_ANNEALING_RATE = LEARNING_RATE * (T * NUM_WORKERS) / NUM_STEPS
#EPSILON_ANNEALING_RATE = EPSILON * (T * NUM_WORKERS) / NUM_STEPS
#





#GAMMA = 0.99
#LAMBDA = 0.95
#EPSILON = 0.1
#LEARNING_RATE = 2.5e-4
#NUM_WORKERS = 8
#T = 128
#EPOCHS = 3
#BATCH_SIZE = 32 * NUM_WORKERS
#RENDER = True
#C1 = 1
#C2 = 0.01
#ENV_MAKER = gym.make
#ENV_ID = "Pong-ram-v0"
#STATE_TYPE = "RAM"
#INPUT_SHAPE = [128, 4]
#ACTIONS = [0, 1, 2, 3, 4, 5]
#NUM_STEPS = 4e7
#LR_ANNEALING_RATE = LEARNING_RATE * (T * NUM_WORKERS) / NUM_STEPS
#EPSILON_ANNEALING_RATE = EPSILON * (T * NUM_WORKERS) / NUM_STEPS
#




GAMMA = 0.99
LAMBDA = 0.95
MAX_GRAD_NORM = 2.0
CLIP_VALUE_LOSS = True
EPSILON = 0.1
LEARNING_RATE = 2.5e-4
NUM_WORKERS = 4
T = 128
NUM_EPOCHS = 8
NUM_MINIBATCHES = 8
RENDER = True
C1 = 1.
C2 = 0.01
ENV_ID = "PongNoFrameskip-v4"
STATE_TYPE = "PIXELS"
INPUT_SHAPE = [4, 84, 84]
ACTIONS = [0, 1, 2, 3, 4, 5]
NUM_STEPS = 4e7
LR_ANNEALING_RATE = LEARNING_RATE * (T * NUM_WORKERS) / NUM_STEPS
EPSILON_ANNEALING_RATE = EPSILON * (T * NUM_WORKERS) / NUM_STEPS